### ISSUE TITLE
default to `toCoreUtxos` or perhaps `toDashUtxos`?

### ISSUE THREAD

**Issue by coolaj86** [dashhive/dashsight.js#16]
I don't think we have any use for the `InsightUtxo` type.

My one gripe with the `CoreUtxo` that's pretty strong is the use of `satashis`. I want `units` instead (currently 10s of nanos or 100ths of micros as denominated).

However, that's a hard breaking change from existing APIs. Gotta think on it.

**Comment by riongull** [comment]
Let's stick with "satoshis" for now (or whatever Core uses already). 

Satoshi deserves to be honored, especially in the project that is continuing his vision of peer to peer electronic/digital cash (i.e. Dash). 

That way we won't have a breaking change, right?  Seems the best approach for now.

**Comment by coolaj86** [comment]
Fair enough.

Note: rename all occurrences of `units` to `satoshis`

**Comment by coolaj86** [comment]
No breaking change necessary.
